### ISSUE TITLE
How do NETN-ORG, NETN-COM and RPR-Communication relate?

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-COM#10]
I drop the question here, but this is an issue covering three FOM modules. The answer should be captured in the documentation of one of the NETN FOM modules, and I think the best place is NETN-COM.

E.g. guidelines or design best practices on how to relate RPR Receivers/Transmitters and Radio messages with networks defined in NETN-COM. Maybe a better term is the conceptual model behind all these FOM classes.

Possibly we can add NETN-ETR also, w.r.t. the jamming task.

**Comment by ChristianPick** [comment]
Currently the link from NETN-COM to RPR-Com is not modelled. The place it should be included are the TX/RX records of the physical devices within the CommunicationNode objects. Additionally it might be necessary to include something in the according variant within PhysicalNetwork. The plan was (at least for radios) to reference the RPR-Com objects to describe the physical parameters of the transmitters. Jamming etc. should be described using the RPR-Com classes, too. An interesting issue will be how to calculate the load of the network. Currently nothing is defined how to do so. The "operational size" of a message is not known and not all messages must be transported using the FOM. Systems could establish peer-to-peer socket connections and use the connectivity-information of NETN-COM to decide wether the communication works or not. The data itself is not seen by the communication simulation this way.

**Comment by bergtwvd** [comment]
Although there might not be explicit relationships modelled between the FOM modules at this point, federation agreements about how they should be used in conjunction should still be documented. E.g. certain behavior or assumptions made.

E.g. the ETR task JamCommunication: here is the assumption that a certain NETN-COM object instance gets created?

**Comment by ChristianPick** [comment]
> E.g. the ETR task JamCommunication: here is the assumption that a certain NETN-COM object instance gets created?

As discussed in https://github.com/AMSP-04/NETN-ETR/issues/34#issuecomment-658470015 I would do so for now as this would be sufficient for now and the physical layer is not specified in detail. The question is should we describe the effect based on the communication or physical network, against an area or entity, and so on. Maybe a variant structure would be a good way. How would you model it?

**Comment by lofstrandbjorn** [comment]
Cross module description and use is out in NETN-FOM module descriptions. See issue https://github.com/AMSP-04/NETN-FOM/issues/33

**Comment by lofstrandbjorn** [comment]
Propose the following section in NETN-FOM

### Communication Modelling

In the NETN-FOM there are a number of different modules related to modelling and simulation of communications. 

* NETN-COM and its dependency to RPR-Communication for the representation of logical networks and physical networks.
* NETN-ORG for initialization of communication nodes.
* NETN-ETR for tasking units to disrupt communication or change state of network devices.

Communication can be modelled on different levels of fidelity.

Information and data communication is simulated as messages between simulated units and systems. If there is no model to represent the actual connection status between communicating nodes, all communication is perfect and without any disruption. 
If the representation of connection status is required in the simulation, the NETN-COM module can provide a representation of `CommunicationNode` and individual `Connection` objects that can be used to determine delivery of messages based on the status of connections. This allows the simulation to model the delivery of messages based on an aggregated view of a logical `CommunicationNetwork`.

In some cases, there is a requirement to model the characteristics of physical links in the network. These physical network models can be used to generate a more high-fidelity representation of aggregated communication network. The NETN-COM module provides the means to represent physical network devices used by a `CommunicationNode`, `PhysicalNetwork` and `LinkStates`. This representation is also linked to the RPR-FOM RPR-Communication module objects for representing `RadioTranmitters` and `RadioReceivers` at a higher degree of fidelity. The status and location of transmitters is the basis for determining the `LinkStates` and these can, in turn, be used to model connections in the logical communication network.

To initialize the communication models, the NETN-ORG module uses the MSDL schema for associating communication networks with units and equipment items. The corresponding NETN-ORG FOM module object classes `Unit` and `EquipmentItem` represents the same information as attributes. This information is available to communication simulations and should be used as the basis for creating the `CommunicationNode` objects.

The NETN-COM can also be used to represent disruption effects on communication networks using `DisruptionEffect` objects. These object can be created directly by some exercise control function in the exercise or by tasking simulated units to perform some disruption task. The NETN-ETR FOM module defines the `DisruptCommunication` task that can be sent to a simulated unit in order to perform some activity leading to the creation of one or more `DisruptionEffect` object.
