### ISSUE TITLE
Perspective of Connection objects

### ISSUE THREAD

**Issue by ChristianPick** [AMSP-04/NETN-COM#7]
Sould connection objects representing the relationship between senders and receivers within a communication network associated to the sender or the receiver?

**Comment by ChristianPick** [comment]
Some thoughts about the issue whether the connection object should be from the senders‘ or receivers‘ perspective. First there could be multiple simulations doing the simulation of the connections. Load balancing would take part by assigning connections object to the different simulation – at any time only one simulation is owning the connection object and has therefore to update the values.

The “connection simulation” usually will do something like an A* algorithm on the links provided by the physical link simulation (explicitly or internally doesn’t matter). 

For an outgoing connection this will find the route to the destination node and all devices with the according capabilities (e.g. interceptors, broadcast receivers etc.) will become receivers of the transmission. Representing the connection object from the sender perspective is therefore the “natural” way how the connection is calculated by the connection simulation.

On the other hand we like to do the check whether a transmission has to be rejected or not at the receiver side. Therefore it would be very handy to create the connection object based on the receivers’ perspective. But what would the impact be if there are still multiple connection simulations for load balancing?

If they are based on outgoing connections they will have to transfer ownership of the connections attribute of the connection object very often. In practice this is like a worst-case scenario in describing the connections. The solution would be to do load balancing based on the incoming connections side. The impact of this would be that each simulation responsible for calculating the connection quality will have to permanently calculate all (!) possible routes through the network to find out on which routes transmissions could reach the node as the node itself doesn’t need to be a requested connection destination. This contradicts the load balancing idea as its aim is to avoid multiple routing calculations.

Therefore I think we should stick with the connection objects from the senders’ perspective. If there is a need to calculate the receivers’ perspective the solution could be to publish both perspectives – the connection simulations publishes the senders’ perspective and a dedicated simulation publishes the resulting receivers’ perspective. This could be a single instance as it has no complicated calculations to do. Such an approach could be agreed on in the federation agreement if there is a federate in need of the receivers' perspective. As this adds a level of complexity to the overall system it should be optional.

**Comment by ThomasBrannstrom** [comment]
Hi.

Sorry for the long answer below, but I need to explain a bit on what we’ve been working on before with regards to this,
which was quite the opposite way of looking at things. It’s makes me a bit confused about the suggested solution with outgoing connections.
It’s probably just that my view on this has been the opposite, and that I need to re-thing things, but I still would like to give you my view on this.
 
We had a student at our company doing a thesis work for multi-hop radio routing.
The idea was that it should be easy for the receiving radio federate to get information about if the receiving
radio could listen on the sending radio through a network of radios using multi-hop.
 
He was looking at it from the receiving side perspective.
His task was to calculate that if Radio 1 is sending, can Radio 2 receive what’s being broadcasted through hops over other radios relaying the information?
We have no option on filtering on sending side, since the radio-simulation don’t use HLA as transportation technique.
 
The basic design was that one simulator was creating the information about the links between each radio,
generating a “matrix” published on HLA (using the old NETN-COM FOM).
This just described if one radio could talk directly to another, not relaying data.
 
A multi-hop simulator federate was created that listened on the Radio to Radio matrix.
He had 4 options for the simulator architecture for the multi-hop simulator:
1.       Centralized request:
The receiving radio requests information from the centralized multi-hop simulator through an HLA interaction,
asking the multi-hop simulator if Radio 2 can receive the information that Radio 1 is sending out.
The answer was sent over HLA back to the requesting federate.
2.       Centralized brute-force:
The multi-hop simulator updates all possible paths every second and send out an update of this on HLA.
3.       Distributed request:
The multi-hop simulator was to be distributed out on the receiving Radio federate,
replying on requests if Radio 2 could listen when Radio 1 was sending.
4.       Distributed brute-force:
The multi-hop simulator was to be distributed out on the receiving Radio federate,
doing brute-force calculations for all of the Radio 2 possible connections.

He was using A* algorithm using a distance heuristic.
With 200 nodes he could do a centralized brute-force calculation of all possible paths in less than 1 second.
So load-balancing might not be needed for most cases, but it’s good that you have it in mind.
 
Looking at this system design that our thesis guy did,
how it worked out and with our , I got some questions:
1.       Would it be possible to set up a federation-agreement, where you have to pick between these three?
a.       Senders-side filtering with connection objects describing outgoing connections.
b.       Receiver-side filter with connection objects describing incoming connections.
c.       Using both above.
2.       Why can’t the connection object describe incoming connections and still be load balanced?
Divide up the receiving radios on different hardware/federates and do the simulation on “what can my radio receive through the network”?
3.       Could the receiver possibly request a connection to the sender, instead of vice versa?
Radio 2 is listening on a specific net and would like to get information on which radios he could listen to through multi-hop in case they do send.
What is the difference in complexity on that compare to requesting outgoing connections?
Don’t we need to do just as many calculations?

The suggestion to have a separate federate to create the incoming connections for receivers could work.
But would be interesting to see your views on our ideas and questions above.
 
Regards, Thomas

**Comment by ChristianPick** [comment]
Hello Thomas,

thanks for your comment. I write my thoughts and comments between your text. I'll have to think through a view of your points and  hope to come back to it tomorrow or the day after. Has your student done any comparisions for the different alternatives? It would be interesting to see the thesis results. Are they publicly available?

Regards,
Christian

> We have no option on filtering on sending side, since the radio-simulation don’t use HLA as transportation technique.

In the suggested approach filtering on sending side could be done but is optional (just for optimization). The receiver has to sort out wether he could get the transmission or not. Reason is simply sending / receiving of broadcasts and devices intercepting communication. Be aware the current approach is not limited to radio networks - all kind of communication technology is in scope of the COM module. Even mixed network infrastructures with routing through radios, ethernet, satcom and laser based links are possible.

> The basic design was that one simulator was creating the information about the links between each radio,
> generating a “matrix” published on HLA (using the old NETN-COM FOM).
> This just described if one radio could talk directly to another, not relaying data.

Thats the physical network layer creating LinkStates objects. In this approach there could be multiple simulators doing so. One reason is load balancing (e.g. computation for radio links using multipath propagation with respect to terrain and weather could be very time consuming). Another reason is the possible use of different technologies. There could be a need to implement these in dedicated / specialized simulators, e.g. one for radio, one for satcom...

> A multi-hop simulator federate was created that listened on the Radio to Radio matrix.

Similar to the calculation of connection objects.

> He had 4 options for the simulator architecture for the multi-hop simulator:
> 
> 1. Centralized request:
>    The receiving radio requests information from the centralized multi-hop simulator through an HLA interaction,
>    asking the multi-hop simulator if Radio 2 can receive the information that Radio 1 is sending out.
>    The answer was sent over HLA back to the requesting federate.

Has he ever tested this variant? If I think of maritime scenarios with thousands of vessels all broadcasting AIS data this will flood the network with requests/respones. I don't think this will work.

> 2. Centralized brute-force:
>    The multi-hop simulator updates all possible paths every second and send out an update of this on HLA.

This sounds more or less like the approach I've choosen. Besides it could be multiple simulators and I do not send out an update but update all changes within the connection objects. Maybe we mean the same, but "send out an update" sound like an interaction to me, not an object. Persistancy of the object is an important point as it reduces the network load while updating changes only.

> 3. Distributed request:
>    The multi-hop simulator was to be distributed out on the receiving Radio federate,
>    replying on requests if Radio 2 could listen when Radio 1 was sending.

Sound like a load-balanced version of option 1), but still will flood the network.

> 4. Distributed brute-force:
>    The multi-hop simulator was to be distributed out on the receiving Radio federate,
>    doing brute-force calculations for all of the Radio 2 possible connections.

What exactly do you mean by "distributed out on the receiving Radio federate"? Is it a separate federate on the same computer or is it integrated into the receivers' simulation/federate? There could be IPR issues in a federation to do so.
(I have to think through this solution in detail)

> He was using A* algorithm using a distance heuristic.
> With 200 nodes he could do a centralized brute-force calculation of all possible paths in less than 1 second.
> So load-balancing might not be needed for most cases, but it’s good that you have it in mind.

200 nodes are fine, but as mentioned there are other numbers out there...

> Looking at this system design that our thesis guy did,
> how it worked out and with our , I got some questions:
> 
> 1. Would it be possible to set up a federation-agreement, where you have to pick between these three?
>    a. Senders-side filtering with connection objects describing outgoing connections.
>    b. Receiver-side filter with connection objects describing incoming connections.
>    c. Using both above.

(I'll have to think about this, maybe you have a good idear w.r.t. my comment below.)

> 2. Why can’t the connection object describe incoming connections and still be load balanced?
>    Divide up the receiving radios on different hardware/federates and do the simulation on “what can my radio receive through the network”?

If I calculate the connectivity from the senders' perspective I have to traverse each link between nodes at maximum _once for each outgoing connection_. It's like calculating how far the signal could come. Each relay refreshes the signal and if an interceptor is on the route he will get the transmission, too.
From the receivers' perspective I have to traverse each link _for each possible outgoing connection for each receiver_. Problematic could be the modelling of interceptors in case of ethernet connections. These could receive the transmission only in case the data was routed through the intercepted link, but he is not a receiver (destination) of the communication.

Of course in both cases the routing caluclation has only to be done as long as a route exists. So doing the calculation from the receiver back to the sender increases the complexity and involves some questions how e.g. cyber warfare could be modelled.
Maybe I missed here something - you are welcome to show me a good solution from the receivers' perspective (in fact it would be great to have one as that's the way the receiver could do his job best.)

But to answer your question in short: It is possible to do the calculation from the receivers' perspective and still do load balancing. But I think it will need more computational ressources than from the senders' perspective. 

> 3. Could the receiver possibly request a connection to the sender, instead of vice versa?
>    Radio 2 is listening on a specific net and would like to get information on which radios he could listen to through multi-hop in case they do send.

Difficult to answer. In many scenarios this would be possible. In real life if Alice wants to talk to Bob the communication is initated by Alice even if Bob just wants to listen his music... It's not up to Bob to decide who is talking to him. His only option is to ignore Alice. The implication of turning this paradigm the other way round is hard to foreseen, therefore I would avoid this.

>    What is the difference in complexity on that compare to requesting outgoing connections?
>    Don’t we need to do just as many calculations?

See above.

> The suggestion to have a separate federate to create the incoming connections for receivers could work.
> But would be interesting to see your views on our ideas and questions above.

**Comment by ThomasBrannstrom** [comment]
Hi Christian.

Thanks for feedback.
I am currently on a short vacation, so just some quick answers for now.

Attaching our students report to the mail here.
The report is unfortunately in Swedish, but try a google translate and ask me for details if you want.

The output from the model was supposed to be an object, not interactions. I don’t think he made it that far though.
Plan was to also look at DDM for the output object, to be able to filter on updates that only is interested for “my radio”.

Can most likely give some more input on Monday/Tuesday upcoming week.

Regards, Thomas

**Comment by ChristianPick** [comment]
> Attaching our students report to the mail here. The report is unfortunately in Swedish, but try a google translate and ask me for details if you want.

Attachments seems not to work this way. Maybe you can attach it on github next monday...

Enjoy your vacation!
Christian

**Comment by ThomasBrannstrom** [comment]
[Radio_multihopping_v14.pdf](https://github.com/AMSP-04/NETN-COM/files/4940262/Radio_multihopping_v14.pdf)
